---
platform: linux

image_resource:
  type: docker-image
  source: {repository: python}

inputs:
- name: cf-diff-repo

run:
  path: sh
  args:
  - -ec
  - |
    set -x
    pip3 install pytest mock patch testfixtures
    cd cf-diff-repo
    pytest -v unit_tests
